# Site Settings
title: "IT 블로그"
description: "IT 기술과 개발에 관한 블로그"
url: "https://danielseol9250.github.io"
baseurl: "/ait26"

# Author
author:
  name: "Your Name"
  email: "your.email@example.com"

# Build Settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown Settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gem/
  - vendor/ruby/

